
###################################################################################################
# ALL
###################################################################################################

shuf -n 4737 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_genes/K562_MFR_TFR.bed
shuf -n 2488 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_genes/K562_MF_TFR.bed
shuf -n 2249 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_genes/K562_MR_TFR.bed
shuf -n 2421 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_genes/K562_MFR_TF.bed
shuf -n 2316 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_genes/K562_MFR_TR.bed
shuf -n 2133 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_genes/K562_MFTF_MRTR.bed
shuf -n 2604 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_genes/K562_MFTR_MRTF.bed
shuf -n 5624 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_genes/TK6_MFR_TFR.bed
shuf -n 3022 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_genes/TK6_MF_TFR.bed
shuf -n 2602 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_genes/TK6_MR_TFR.bed
shuf -n 2874 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_genes/TK6_MFR_TF.bed
shuf -n 2750 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_genes/TK6_MFR_TR.bed
shuf -n 2539 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_genes/TK6_MFTF_MRTR.bed
shuf -n 3085 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_genes/TK6_MFTR_MRTF.bed

shuf -n 2311 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_genes/K562_MFR_TFR.bed
shuf -n 1129 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_genes/K562_MF_TFR.bed
shuf -n 1182 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_genes/K562_MR_TFR.bed
shuf -n 1322 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_genes/K562_MFR_TF.bed
shuf -n 989 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_genes/K562_MFR_TR.bed
shuf -n 1031 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_genes/K562_MFTF_MRTR.bed
shuf -n 1280 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_genes/K562_MFTR_MRTF.bed
shuf -n 2903 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_genes/TK6_MFR_TFR.bed
shuf -n 1743 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_genes/TK6_MF_TFR.bed
shuf -n 1160 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_genes/TK6_MR_TFR.bed
shuf -n 1476 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_genes/TK6_MFR_TF.bed
shuf -n 1427 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_genes/TK6_MFR_TR.bed
shuf -n 1287 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_genes/TK6_MFTF_MRTR.bed
shuf -n 1616 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_genes/TK6_MFTR_MRTF.bed

shuf -n 2426 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_genes/K562_MFR_TFR.bed
shuf -n 1359 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_genes/K562_MF_TFR.bed
shuf -n 1067 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_genes/K562_MR_TFR.bed
shuf -n 1099 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_genes/K562_MFR_TF.bed
shuf -n 1327 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_genes/K562_MFR_TR.bed
shuf -n 1102 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_genes/K562_MFTF_MRTR.bed
shuf -n 1324 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_genes/K562_MFTR_MRTF.bed
shuf -n 2721 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_genes/TK6_MFR_TFR.bed
shuf -n 1279 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_genes/TK6_MF_TFR.bed
shuf -n 1442 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_genes/TK6_MR_TFR.bed
shuf -n 1398 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_genes/TK6_MFR_TF.bed
shuf -n 1323 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_genes/TK6_MFR_TR.bed
shuf -n 1252 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_genes/TK6_MFTF_MRTR.bed
shuf -n 1469 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_genes/TK6_MFTR_MRTF.bed

shuf -n 2307 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_promoters/K562_MFR_TFR.bed
shuf -n 1241 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_promoters/K562_MF_TFR.bed
shuf -n 1066 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_promoters/K562_MR_TFR.bed
shuf -n 1230 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllPromPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_promoters/K562_MFR_TF.bed
shuf -n 1077 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllPromMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_promoters/K562_MFR_TR.bed
shuf -n 1478 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_promoters/K562_MFTF_MRTR.bed
shuf -n 829 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_promoters/K562_MFTR_MRTF.bed
shuf -n 1873 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_promoters/TK6_MFR_TFR.bed
shuf -n 979 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_promoters/TK6_MF_TFR.bed
shuf -n 894 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_promoters/TK6_MR_TFR.bed
shuf -n 915 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllPromPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_promoters/TK6_MFR_TF.bed
shuf -n 958 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllPromMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_promoters/TK6_MFR_TR.bed
shuf -n 1012 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_promoters/TK6_MFTF_MRTR.bed
shuf -n 861 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/all_promoters/TK6_MFTR_MRTF.bed

shuf -n 1296 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_promoters/K562_MFR_TFR.bed
shuf -n 629 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_promoters/K562_MF_TFR.bed
shuf -n 667 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_promoters/K562_MR_TFR.bed
shuf -n 612 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusPromPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_promoters/K562_MFR_TF.bed
shuf -n 684 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusPromMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_promoters/K562_MFR_TR.bed
shuf -n 740 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_promoters/K562_MFTF_MRTR.bed
shuf -n 556 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_promoters/K562_MFTR_MRTF.bed
shuf -n 959 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_promoters/TK6_MFR_TFR.bed
shuf -n 520 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_promoters/TK6_MF_TFR.bed
shuf -n 439 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_promoters/TK6_MR_TFR.bed
shuf -n 458 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusPromPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_promoters/TK6_MFR_TF.bed
shuf -n 501 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusPromMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_promoters/TK6_MFR_TR.bed
shuf -n 535 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_promoters/TK6_MFTF_MRTR.bed
shuf -n 424 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/active_promoters/TK6_MFTR_MRTF.bed

shuf -n 1011 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_promoters/K562_MFR_TFR.bed
shuf -n 612 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_promoters/K562_MF_TFR.bed
shuf -n 399 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_promoters/K562_MR_TFR.bed
shuf -n 618 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusPromPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_promoters/K562_MFR_TF.bed
shuf -n 393 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusPromMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_promoters/K562_MFR_TR.bed
shuf -n 738 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_promoters/K562_MFTF_MRTR.bed
shuf -n 273 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_promoters/K562_MFTR_MRTF.bed
shuf -n 914 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_promoters/TK6_MFR_TFR.bed
shuf -n 459 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_promoters/TK6_MF_TFR.bed
shuf -n 455 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_promoters/TK6_MR_TFR.bed
shuf -n 457 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusPromPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_promoters/TK6_MFR_TF.bed
shuf -n 457 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusPromMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_promoters/TK6_MFR_TR.bed
shuf -n 477 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_promoters/TK6_MFTF_MRTR.bed
shuf -n 437 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/inactive_promoters/TK6_MFTR_MRTF.bed

shuf -n 12716 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfIntergenicPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/intergenic/K562_restMF.bed
shuf -n 13153 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfIntergenicMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/intergenic/K562_restMR.bed
shuf -n 19633 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfIntergenicPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/intergenic/TK6_restMF.bed
shuf -n 18309 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfIntergenicMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/all/intergenic/TK6_restMR.bed

###################################################################################################
# A
###################################################################################################

shuf -n 126 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_genes/K562_MFR_TFR.bed
shuf -n 70 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_genes/K562_MF_TFR.bed
shuf -n 56 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_genes/K562_MR_TFR.bed
shuf -n 65 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_genes/K562_MFR_TF.bed
shuf -n 61 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_genes/K562_MFR_TR.bed
shuf -n 67 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_genes/K562_MFTF_MRTR.bed
shuf -n 59 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_genes/K562_MFTR_MRTF.bed
shuf -n 388 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_genes/TK6_MFR_TFR.bed
shuf -n 210 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_genes/TK6_MF_TFR.bed
shuf -n 178 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_genes/TK6_MR_TFR.bed
shuf -n 197 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_genes/TK6_MFR_TF.bed
shuf -n 191 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_genes/TK6_MFR_TR.bed
shuf -n 204 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_genes/TK6_MFTF_MRTR.bed
shuf -n 184 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_genes/TK6_MFTR_MRTF.bed

shuf -n 84 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_genes/K562_MFR_TFR.bed
shuf -n 43 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_genes/K562_MF_TFR.bed
shuf -n 41 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_genes/K562_MR_TFR.bed
shuf -n 52 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_genes/K562_MFR_TF.bed
shuf -n 32 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_genes/K562_MFR_TR.bed
shuf -n 45 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_genes/K562_MFTF_MRTR.bed
shuf -n 39 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_genes/K562_MFTR_MRTF.bed
shuf -n 216 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_genes/TK6_MFR_TFR.bed
shuf -n 113 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_genes/TK6_MF_TFR.bed
shuf -n 103 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_genes/TK6_MR_TFR.bed
shuf -n 110 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_genes/TK6_MFR_TF.bed
shuf -n 106 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_genes/TK6_MFR_TR.bed
shuf -n 115 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_genes/TK6_MFTF_MRTR.bed
shuf -n 101 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_genes/TK6_MFTR_MRTF.bed

shuf -n 42 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_genes/K562_MFR_TFR.bed
shuf -n 27 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_genes/K562_MF_TFR.bed
shuf -n 15 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_genes/K562_MR_TFR.bed
shuf -n 13 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_genes/K562_MFR_TF.bed
shuf -n 29 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_genes/K562_MFR_TR.bed
shuf -n 22 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_genes/K562_MFTF_MRTR.bed
shuf -n 20 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_genes/K562_MFTR_MRTF.bed
shuf -n 172 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_genes/TK6_MFR_TFR.bed
shuf -n 97 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_genes/TK6_MF_TFR.bed
shuf -n 75 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_genes/TK6_MR_TFR.bed
shuf -n 87 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_genes/TK6_MFR_TF.bed
shuf -n 85 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_genes/TK6_MFR_TR.bed
shuf -n 89 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_genes/TK6_MFTF_MRTR.bed
shuf -n 83 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_genes/TK6_MFTR_MRTF.bed

shuf -n 173 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_promoters/K562_MFR_TFR.bed
shuf -n 93 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_promoters/K562_MF_TFR.bed
shuf -n 80 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_promoters/K562_MR_TFR.bed
shuf -n 82 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllPromPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_promoters/K562_MFR_TF.bed
shuf -n 91 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllPromMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_promoters/K562_MFR_TR.bed
shuf -n 89 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_promoters/K562_MFTF_MRTR.bed
shuf -n 84 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_promoters/K562_MFTR_MRTF.bed
shuf -n 125 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_promoters/TK6_MFR_TFR.bed
shuf -n 67 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_promoters/TK6_MF_TFR.bed
shuf -n 58 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_promoters/TK6_MR_TFR.bed
shuf -n 63 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllPromPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_promoters/TK6_MFR_TF.bed
shuf -n 62 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllPromMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_promoters/TK6_MFR_TR.bed
shuf -n 65 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_promoters/TK6_MFTF_MRTR.bed
shuf -n 60 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/all_promoters/TK6_MFTR_MRTF.bed

shuf -n 75 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_promoters/K562_MFR_TFR.bed
shuf -n 42 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_promoters/K562_MF_TFR.bed
shuf -n 33 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_promoters/K562_MR_TFR.bed
shuf -n 37 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusPromPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_promoters/K562_MFR_TF.bed
shuf -n 38 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusPromMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_promoters/K562_MFR_TR.bed
shuf -n 40 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_promoters/K562_MFTF_MRTR.bed
shuf -n 35 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_promoters/K562_MFTR_MRTF.bed
shuf -n 58 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_promoters/TK6_MFR_TFR.bed
shuf -n 37 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_promoters/TK6_MF_TFR.bed
shuf -n 21 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_promoters/TK6_MR_TFR.bed
shuf -n 31 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusPromPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_promoters/TK6_MFR_TF.bed
shuf -n 27 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusPromMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_promoters/TK6_MFR_TR.bed
shuf -n 34 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_promoters/TK6_MFTF_MRTR.bed
shuf -n 24 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/active_promoters/TK6_MFTR_MRTF.bed

shuf -n 98 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_promoters/K562_MFR_TFR.bed
shuf -n 51 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_promoters/K562_MF_TFR.bed
shuf -n 47 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_promoters/K562_MR_TFR.bed
shuf -n 45 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusPromPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_promoters/K562_MFR_TF.bed
shuf -n 53 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusPromMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_promoters/K562_MFR_TR.bed
shuf -n 49 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_promoters/K562_MFTF_MRTR.bed
shuf -n 49 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_promoters/K562_MFTR_MRTF.bed
shuf -n 67 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_promoters/TK6_MFR_TFR.bed
shuf -n 30 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_promoters/TK6_MF_TFR.bed
shuf -n 37 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_promoters/TK6_MR_TFR.bed
shuf -n 32 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusPromPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_promoters/TK6_MFR_TF.bed
shuf -n 35 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusPromMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_promoters/TK6_MFR_TR.bed
shuf -n 31 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_promoters/TK6_MFTF_MRTR.bed
shuf -n 36 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/inactive_promoters/TK6_MFTR_MRTF.bed

shuf -n 10314 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfIntergenicPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/intergenic/K562_restMF.bed
shuf -n 12342 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfIntergenicMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/intergenic/K562_restMR.bed
shuf -n 17013 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfIntergenicPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/intergenic/TK6_restMF.bed
shuf -n 16569 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfIntergenicMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/a/intergenic/TK6_restMR.bed

###################################################################################################
# B
###################################################################################################

shuf -n 4611 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_genes/K562_TIO.bed
shuf -n 2317 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_genes/K562_TO.bed
shuf -n 1421 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfInLoopAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_genes/K562_TI.bed
shuf -n 452 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopAllGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_genes/K562_TF.bed
shuf -n 421 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopAllGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_genes/K562_TR.bed
shuf -n 873 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_genes/K562_TFR.bed
shuf -n 5236 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_genes/TK6_TIO.bed
shuf -n 2361 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_genes/TK6_TO.bed
shuf -n 1027 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfInLoopAllGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_genes/TK6_TI.bed
shuf -n 1138 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopAllGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_genes/TK6_TF.bed
shuf -n 710 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopAllGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_genes/TK6_TR.bed
shuf -n 1848 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_genes/TK6_TFR.bed

shuf -n 2227 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_genes/K562_TIO.bed
shuf -n 1102 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_genes/K562_TO.bed
shuf -n 689 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfInLoopPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_genes/K562_TI.bed
shuf -n 231 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopPlusGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_genes/K562_TF.bed
shuf -n 205 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopPlusGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_genes/K562_TR.bed
shuf -n 436 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_genes/K562_TFR.bed
shuf -n 2687 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_genes/TK6_TIO.bed
shuf -n 1205 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_genes/TK6_TO.bed
shuf -n 520 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfInLoopPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_genes/TK6_TI.bed
shuf -n 514 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopPlusGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_genes/TK6_TF.bed
shuf -n 448 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopPlusGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_genes/TK6_TR.bed
shuf -n 962 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopPlusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_genes/TK6_TFR.bed

shuf -n 2384 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_genes/K562_TIO.bed
shuf -n 1215 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_genes/K562_TO.bed
shuf -n 732 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfInLoopMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_genes/K562_TI.bed
shuf -n 221 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopMinusGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_genes/K562_TF.bed
shuf -n 216 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopMinusGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_genes/K562_TR.bed
shuf -n 437 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_genes/K562_TFR.bed
shuf -n 2549 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_genes/TK6_TIO.bed
shuf -n 1156 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_genes/TK6_TO.bed
shuf -n 507 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfInLoopMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_genes/TK6_TI.bed
shuf -n 624 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopMinusGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_genes/TK6_TF.bed
shuf -n 262 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopMinusGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_genes/TK6_TR.bed
shuf -n 886 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopMinusGene.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_genes/TK6_TFR.bed

shuf -n 2134 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_promoters/K562_TIO.bed
shuf -n 1238 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_promoters/K562_TO.bed
shuf -n 412 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfInLoopAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_promoters/K562_TI.bed
shuf -n 285 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopAllPromPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_promoters/K562_TF.bed
shuf -n 199 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopAllPromMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_promoters/K562_TR.bed
shuf -n 484 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_promoters/K562_TFR.bed
shuf -n 1748 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_promoters/TK6_TIO.bed
shuf -n 1034 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_promoters/TK6_TO.bed
shuf -n 524 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfInLoopAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_promoters/TK6_TI.bed
shuf -n 112 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopAllPromPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_promoters/TK6_TF.bed
shuf -n 78 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopAllPromMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_promoters/TK6_TR.bed
shuf -n 190 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopAllProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/all_promoters/TK6_TFR.bed

shuf -n 1221 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_promoters/K562_TIO.bed
shuf -n 568 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_promoters/K562_TO.bed
shuf -n 203 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfInLoopPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_promoters/K562_TI.bed
shuf -n 267 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopPlusPromPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_promoters/K562_TF.bed
shuf -n 183 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopPlusPromMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_promoters/K562_TR.bed
shuf -n 450 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_promoters/K562_TFR.bed
shuf -n 901 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_promoters/TK6_TIO.bed
shuf -n 621 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_promoters/TK6_TO.bed
shuf -n 251 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfInLoopPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_promoters/TK6_TI.bed
shuf -n 16 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopPlusPromPLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_promoters/TK6_TF.bed
shuf -n 13 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopPlusPromMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_promoters/TK6_TR.bed
shuf -n 29 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopPlusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/active_promoters/TK6_TFR.bed

shuf -n 913 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_promoters/K562_TIO.bed
shuf -n 670 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_promoters/K562_TO.bed
shuf -n 209 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfInLoopMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_promoters/K562_TI.bed
shuf -n 18 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopMinusGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_promoters/K562_TF.bed
shuf -n 16 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopMinusGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_promoters/K562_TR.bed
shuf -n 34 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoopMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_promoters/K562_TFR.bed
shuf -n 847 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_promoters/TK6_TIO.bed
shuf -n 413 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_promoters/TK6_TO.bed
shuf -n 273 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfInLoopMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_promoters/TK6_TI.bed
shuf -n 96 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopMinusGenePLUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_promoters/TK6_TF.bed
shuf -n 65 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopMinusGeneMINUS.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_promoters/TK6_TR.bed
shuf -n 161 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoopMinusProm.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/inactive_promoters/TK6_TFR.bed

shuf -n 3213 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoop.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/intergenic/K562_rest.bed
shuf -n 1069 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfInLoop.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/intergenic/K562_restIN.bed
shuf -n 2144 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/K562_allCtcfOutLoop.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/intergenic/K562_restOUT.bed
shuf -n 4360 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoop.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/intergenic/TK6_rest.bed
shuf -n 1382 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfInLoop.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/intergenic/TK6_restIN.bed
shuf -n 2972 /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/23_Final_CTCF_LOOP/5_CTCFatAllFeatures/GM12878_allCtcfOutLoop.bed > /media/egg/cheops_agpapan/eduardo/Roukos_Bliss/Results/26_Final_CTCF_All/0_input/intersection/b/intergenic/TK6_restOUT.bed


